#pragma once

#include "cpu_ops.hpp"

namespace gehmboi::emulator {
static const std::unordered_map<uint8_t, Opcode> block0Map = {
    // BLOCK_0_LD_R16_IMM16
    {0x01,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R16_IMM16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::BC, false,
                                                 false, false),
         CPUOperationOperand::createImm16Operand(false),
     }},
    {0x11,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R16_IMM16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::DE, false,
                                                 false, false),
         CPUOperationOperand::createImm16Operand(false),
     }},
    {0x21,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R16_IMM16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, false,
                                                 false, false),
         CPUOperationOperand::createImm16Operand(false),
     }},
    {0x31,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R16_IMM16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::SP, false,
                                                 false, false),
         CPUOperationOperand::createImm16Operand(false),
     }},
    // BLOCK_0_LD_R16MEM_A
    {0x02,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R16MEM_A,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::BC, true,
                                                 false, false),
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
     }},
    {0x12,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R16MEM_A,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::DE, true,
                                                 false, false),
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
     }},
    {0x22,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R16MEM_A,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, true,
                                                 true, false),
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
     }},
    {0x32,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R16MEM_A,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, true,
                                                 false, true),
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
     }},
    // BLOCK_0_LD_A_R16MEM
    {0x0A,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_A_R16MEM,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::BC, true,
                                                 false, false),
     }},
    {0x1A,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_A_R16MEM,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::DE, true,
                                                 false, false),
     }},
    {0x2A,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_A_R16MEM,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, true,
                                                 true, false),
     }},
    {0x3A,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_A_R16MEM,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, true,
                                                 false, true),
     }},
    // BLOCK_0_INC_R16
    {0x03,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::BC, false,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x13,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::DE, false,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x23,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, false,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x33,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::SP, false,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    // BLOCK_0_DEC_R16
    {0x0B,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::BC, false,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x1B,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::DE, false,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x2B,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, false,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x3B,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::SP, false,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    // BLOCK_0_ADD_HL_R16
    {0x09,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_ADD_HL_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL,
                                                 false, false, false),
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::BC,
                                                 false, false, false),
     }},
    {0x19,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_ADD_HL_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL,
                                                 false, false, false),
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::DE,
                                                 false, false, false),
     }},
    {0x29,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_ADD_HL_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL,
                                                 false, false, false),
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL,
                                                 false, false, false),
     }},
    {0x39,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_ADD_HL_R16,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL,
                                                 false, false, false),
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::SP,
                                                 false, false, false),
     }},
    // BLOCK_0_INC_R8
    {0x04,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::B, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x0C,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::C, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x14,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::D, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x1C,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::E, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x24,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::H, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x2C,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::L, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x34,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R8,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, true,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x3C,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_INC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
         CPUOperationOperand::createNoOperand(),
     }},
    // BLOCK_0_DEC_R8
    {0x05,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::B, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x0D,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::C, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x15,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::D, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x1D,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::E, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x25,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::H, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x2D,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::L, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x35,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R8,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, true,
                                                 false, false),
         CPUOperationOperand::createNoOperand(),
     }},
    {0x3D,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_DEC_R8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
         CPUOperationOperand::createNoOperand(),
     }},
    // BLOCK_0_LD_R8_IMM8
    {0x06,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R8_IMM8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::B, false),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x0E,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R8_IMM8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::C, false),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x16,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R8_IMM8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::D, false),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x1E,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R8_IMM8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::E, false),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x26,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R8_IMM8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::H, false),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x2E,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R8_IMM8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::L, false),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x36,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R8_IMM8,
         CPUOperationOperand::createReg16Operand(CPURegister16Enum::HL, true,
                                                 false, false),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x3E,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_LD_R8_IMM8,
         CPUOperationOperand::createReg8Operand(CPURegister8Enum::A, false),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x20,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_JR_COND_IMM8,
         CPUOperationOperand::createConditionOperand(CPUConditionEnum::NZ),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x28,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_JR_COND_IMM8,
         CPUOperationOperand::createConditionOperand(CPUConditionEnum::Z),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x30,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_JR_COND_IMM8,
         CPUOperationOperand::createConditionOperand(CPUConditionEnum::NC),
         CPUOperationOperand::createImm8Operand(false),
     }},
    {0x38,
     Opcode{
         CPUOperationTypeEnum::BLOCK_0_JR_COND_IMM8,
         CPUOperationOperand::createConditionOperand(CPUConditionEnum::C),
         CPUOperationOperand::createImm8Operand(false),
     }},
};
} // namespace gehmboi::emulator